account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout, logout_then_login
from django.contrib.auth.views import password_change, password_change_done
from django.contrib.auth.views import password_reset, password_reset_done,\
    password_reset_confirm, password_reset_complete

urlpatterns = [
    # 登陆注销
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^logout-then-login/$', logout_then_login, name='logout_then_login'),
    # 修改密码
    url(r'^password-change/$', password_change, name='password_change'),
    url(r'^password-change/done/$', password_change_done, name='password_change_done'),
    # 重置密码
    url(r'^password-reset/$', password_reset, name='password_reset'),
    url(r'^password-reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        password_reset_confirm, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', password_reset_complete, name='password_reset_complete'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # 用户注册以及编辑
    url(r'^register/$', views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit'),
    # 用户列表以及详情
    url(r'^users/$', views.user_list, name='user_list'),
    url(r"^users/follow/$", views.user_follow, name="user_follow"),
    url(r'^users/(?P<username>[-\w]+)/$', views.user_detail, name='user_detail'),

]

bookmarks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^detail/(?P<id>[\d]+)/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^list/$', views.image_list, name='list'),
    url(r'^ranking/$', views.image_ranking, name='ranking'),
]

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    date_of_birth = models.DateField(blank=True, null=True)  # 默认为空 可以不填
    photo = models.FileField(upload_to='users/%Y/%m/%d', blank=True)

    def __str__(self):
        return 'Profile for {}'.format(self.user)


class Contact(models.Model):
    user_from = models.ForeignKey(User, related_name='rel_from_set')
    user_to = models.ForeignKey(User, related_name='rel_to_set')
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)


User.add_to_class('following', models.ManyToManyField('self',
                                                      through=Contact,
                                                      related_name='followers',
                                                      symmetrical=False))

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                               widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data  # cleaned_data 清洗数据 留下关键数据
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Password don't match.")
        return cd['password2']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

account/views.py
from django.shortcuts import render
from .forms import LoginForm, UserRegistrationForm, UserForm, ProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from .models import Contact  # 用这个中间模型来创建用户关系
from actions.utils import create_action
from actions.models import Action
# Create your views here.


@login_required
def dashboard(request):
    actions = Action.objects.exclude(user=request.user)  # 获取除了自己之外的所有用户动作
    following_ids = request.user.following.values_list('id', flat=True)  # 取得所有请求用户关注人的id
    if following_ids:
        actions = Action.objects.filter(user_id__in=following_ids)\
            .select_related('user', 'user__profile').prefetch_related('target')  # 过滤取得关注人的动作
    actions = actions[:10]  # 如果没关注任何人就显示所有用户的动作10条 关注了就显示关注用户的
    return render(request,
                  'account/dashboard.html',
                  {'section': 'dashboard',
                   'actions': actions})  # section变量跟踪用户正在查看的页面


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # 新建一个用户但是不立马保存到数据库
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            create_action(new_user, "has created an account")
            profile = Profile.objects.create(user=new_user)
            # 定向到注册成功页面
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserForm(instance=request.user,data=request.POST)
        profile_form = ProfileForm(instance=request.user.profile,
                                   data=request.POST,
                                   files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updated your profile')

    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request,
                  'account/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


@login_required
def user_list(request):
    users = User.objects.exclude(id=request.user.id).filter(is_active=True)   # 获取激活状态的用户
    return render(request, 'account/user/list.html',
                  {'section': 'people',
                   'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'account/user/detail.html',
                  {'section': 'people',
                   'user': user})


@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(
                    user_from=request.user,
                    user_to=user)
                create_action(request.user, " is following", user)
            else:
                Contact.objects.filter(user_from=request.user,
                                       user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})

account/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/
jquery.min.js"></script>
<script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.
cookie.min.js "></script>
<script>
    var csrftoken = $.cookie('csrftoken');//从cookie取得当前token值
    function csrfSafeMethod(method) {
        //不需要保护的请求头
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain){
        xhr.setRequestHeader("x-CSRFToken", csrftoken);
    }
        }
    });
</script>
<script>
    $(document).ready(function () {
        {% block domready %}
        {% endblock %}
    });
</script>
<body>
    <div id="header">
        <span class="logo">Bookmarks</span>
        {% if user.is_authenticated %}
            <ul class="menu">
                <li {% if section == 'dashboard' %} class="selected"{% endif %}><a href="{% url 'dashboard' %}">My dashboard</a> </li>
                <li {% if section == 'images' %} class="selected"{% endif %}><a href="{% url 'images:list' %}">Images</a> </li>
                <li {% if section == 'people' %} class="selected" {% endif %}><a href="{% url 'user_list' %}">People</a> </li>
            </ul>
        {% endif %}
        <span class="user">
            {% if user.is_authenticated %}
            Hello {{ request.user.first_name }},
            <a href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'login' %}">Log-in</a>
            {% endif %}
        </span>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
                <a href="#" class="close"></a>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>