bookmarks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^detail/(?P<id>[\d]+)/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^list/$', views.image_list, name='list'),
    url(r'^ranking/$', views.image_ranking, name='ranking'),
]

images/models.py
from django.db import models
from django.conf import settings
from uuslug import slugify
from django.core.urlresolvers import reverse


# Create your models here.


class Image(models.Model):
    """图片模型"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created')  # 图片关联的用户
    title = models.CharField(max_length=125)
    slug = models.SlugField(max_length=200, blank=True)  # 一个只包含数字字母下划线连字符的短标签
    url = models.URLField()
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    created = models.DateField(auto_now_add=True,
                               db_index=True)  # db_index=Ture Django 将会为这个字段创建索引
    user_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       related_name='images_liked',
                                       blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            super(Image, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=(self.id, self.slug))

images/forms.py
from django import forms
from .models import Image
from django.core.files.base import ContentFile
from uuslug import slugify
from urllib import request


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('url', 'title', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url

    def save(self, force_insert=False,
             force_update=False,
             commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = slugify(image.title)
        response = request.urlopen(image_url)
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ImageCreateForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Image
from django.views.decorators.http import require_POST
from django.http import JsonResponse, HttpResponse
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from common.decorators import ajax_required
from actions.utils import create_action
# 设置redis
import redis
from django.conf import settings

# 连接redis
r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)


@login_required
def image_create(request):
    """创建图片的视图 通过点击一个javascript书签"""
    if request.method == "POST":
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user, "bookmarked image", new_image)
            messages.success(request, "Image added successfully")
            return redirect(new_image.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)  # GET请求带url地址
    return render(request, 'images/image/create.html', {'form': form})


@login_required
def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    total_views = r.incr('image:{}:views'.format(image.id))  # object-type:id:field
    r.zincrby('image_ranking', image.id, 1)
    return render(request, 'images/image/detail.html', {'section': 'images',
                                                        'image': image,
                                                        'total_views': total_views})


def get_image_likes(image):
    user_username = [i.username for i in image.user_like.all()]
    user_first_name = [i.first_name for i in image.user_like.all()]
    user_photo_url = [i.profile.photo.url for i in image.user_like.all()]
    result = {i: [j, k] for i, j, k in zip(user_username, user_first_name, user_photo_url)}
    return result


@ajax_required
@require_POST
@login_required
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    # 获取ajax提交的id跟动作后从模型取得实例
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.user_like.add(request.user)
                create_action(request.user, "likes", image)

            else:
                image.user_like.remove(request.user)
            user_dict = get_image_likes(image)
            return JsonResponse(user_dict)
        except:
            pass
    return JsonResponse({'status': 'ko'})


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)  # 如果获取到page页码不是证书 获取第一页图片实例
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'images/image/list_ajax.html',
                      {"section": 'images', "images": images})  # 返回一段html
    return render(request, 'images/image/list.html',
                  {'section': 'images', 'images': images})


@login_required
def image_ranking(request):
    image_ranking= r.zrange('image_ranking', 0, -1, desc=True)[:10]
    print(image_ranking)
    image_ranking_ids = [int(id) for id in image_ranking]
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request, "images/image/ranking.html",
                  {"section": 'images',
                   'most_viewed': most_viewed})

images/templates/images/image/create.html
{% extends 'base.html' %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="." method="post">
    {{ form.as_p }}
    <input type="submit" value="Bookmark it!">
    {% csrf_token %}
    </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends 'base.html' %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
    <h1>{{ image.title }}</h1>
   {% load thumbnail %}
    {% thumbnail image.image "300x300" crop="100%" as im %}
        <a href="{{ image.image.url }}">
            <img src="{{ im.url }}" class="image-detail">
        </a>
    {% endthumbnail %}
    {% with total_likes=image.user_like.count users_like=image.user_like.all%}
    <div class="image-info">
        <div>
            <span class="count">
                <span class="total">{{ total_likes }}</span>
                like{{ total_likes|pluralize }}
            </span>
            <span class="count">
                <span class="total">{{ total_views }}</span>
                view{{ total_views|pluralize }}
            </span>
        <a href="#" data-id="{{ image.id }}"
           data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
        {% if request.user in users_like %}
        Unlike
        {% else %}
        Like
        {% endif %}
        </a>
        </div>
        {{ image.description|linebreaks }}
    <div class="image-likes">
        {% for user in image.user_like.all %}
            <div>
                <img src="{{ user.profile.photo.url }}">
                <p>{{ user.first_name }}</p>
            </div>
        {% empty %}
            <p class="error" >No body likes this images yet.</p>
        {% endfor %}
    </div>
{% endwith %}
    </div>
{% endblock %}
{% block domready %}
    $('a.like').click(function(e){
        e.preventDefault();
        $.post('{% url "images:like" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){
                if (data['status'] !== 'ko')
                {
                    var previous_action = $('a.like').data('action');

                    // 更换 data-action
                    $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                    // toggle link text
                    $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

                    // 更新 total likes
                    var previous_likes = parseInt($('span.count .total').text()); //获取当前字符串转换成数字
                    $('span.count .total').text(previous_action == 'like' ? previous_likes += 1 : previous_likes -= 1);
                    divs = ''
                    for(i in data){
                            div = "<div><img src="+ data[i][1] + "><p>" + data[i][0]+'</p></div>'
                            divs += div
                            }

                $('.image-likes').html(parseInt($('span.count .total').text()) == 0 ?
                '<p class="error"> No body likes this images yet.</p>':divs)
                $('span.count').html(previous_likes == 1? '<span class="total">1</span> like' :
                '<span class="total">'+previous_likes+'</span> likes')





                }
        });

    });
{% endblock %}

images/templates/images/image/list.html
{% extends 'base.html' %}
{% block title %}Images bookmarked{% endblock %}
{% block content %}
    <h1>Images bookmarked</h1>
    <div id="image-list">
        {% include 'images/image/list_ajax.html' %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
		    block_request = true;
		    page += 1;
		    $.get('?page=' + page, function(data) {
		        if(data == '')
		        {
		            empty_page = true;
		        }
		        else {
                    block_request = false;
                    $('#image-list').append(data);
    	        }
            });
    	}
    });
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}
{% load staticfiles %}

{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image "300x300" crop="100%" as im %}
            <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}">
            </a>
            {% endthumbnail %}
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
            {{ image.title }}
            </a>
        </div>
    </div>
{% endfor %}

images/templates/images/image/ranking.html
{% extends 'base.html' %}
{% block title %}Images ranking{% endblock %}

{% block content %}
    <h1>Image ranking</h1>
    <ol>
        {% for image in most_viewed %}
            <li>
            <a href="{{ image.get_absolute_url }}">{{ image.title }}</a>
            </li>
        
        {% endfor %}
        
    </ol>
{% endblock %}